#!/bin/sh

# Author: Patrik Svestka
# Licence: MIT

# Note: Inspired by Akkana's kitfox patch - "kitfox: make a customized Firefox."

# Removes most of the original keyboard shortcuts from Thunderbird
# Unpacks thunderbirds/omni.ja, apply patches and then packs it back.

# Either run this from the downloaded and unpacked Thunderbird directory,
# or pass the path to that directory as the first argument.

# On a system where thunderbird is installed as a package, pass it the
# location of the thunderbird files, e.g. /usr/lib64/thunderbird on Opensuse.

# The tricky part is that sometimes updates break Thunderbird and you need to repatch it.
#
# WARNING: Sometimes re-patching is needed when Thunderbird updates itself and changes omni.ja
#   Re-patching already patched version does not work!  The changes are already there.  
#   You need to download new version of Thunderbird, re-patch the omni.ja again!


THUNDERBIRDDIR=$1
if [ x"$THUNDERBIRDDIR" = "x" ]; then
  echo "Pass location of thunderbird files, e.g. /usr/lib64/thunderbird or /usr/lib/thunderbird"
  exit 1
else
  # In zsh, $THUNDERBIRDDIR:A would do this.
  THUNDERBIRDDIR=$(realpath $THUNDERBIRDDIR)
fi

if [ ! -d "$THUNDERBIRDDIR" ]; then
  echo 'Usage: thunderbird-patch [THUNDERBIRDDIR]'
  exit 1
fi

echo Thunderbird dir is: $THUNDERBIRDDIR

echo checking if $THUNDERBIRDDIR/thunderbird is running ...
pgrep thunderbird -la|grep $THUNDERBIRDDIR/thunderbird;
if [ $? -eq 0 ]; then
  echo 'thunderbird is still running!'
  exit 1
fi

realomnipath=$THUNDERBIRDDIR/omni.ja
OMNITMPDIR=/tmp/omni
BACKUP_OMNI=thunderbird-omni.ja.backup-$(date +%Y-%m-%d_%H:%m:%S).ja

U=${SUDO_USER:-$USER}
HOMEDIR=/home/$U

echo "Making directory $OMNITMPDIR ..."
mkdir $OMNITMPDIR
cd $OMNITMPDIR

echo "Unzipping in $OMNITMPDIR ..."https://github.com/tukanos/scripts.git
unzip -q $realomnipath

echo "creating a backup ${OMNITMPDIR}-bak/ before making changes ..."
cp -a $OMNITMPDIR ${OMNITMPDIR}-bak

echo "Making changes ..."

########################################
# PUT YOUR DESIRED CHANGE HERE.

# remove most of the annoying thunderbird keyboard shortcuts
sed -i -e '#/^\s*<!ENTITY [^\.]*Cmd\.key "/{  s:^\s*:<!-- :; s:$: -->: ;}' \
    -i -e '/^\s*<key id="key_[^"]*" key="&[^\.]*Cmd\.key;"[^/]*\/[^>]*>$/ { s:^\s*:<!-- :; s:$: -->: ; };' \
    -i -e ':a /^\s*<key id="key_[^"]*" key="&[^\.]*Cmd\.key.*;"$/ { N; s:\n: :; s:^\s*:<!-- :; s:$: -->: ;ta; };' \
chrome/en-US/locale/en-US/messenger/messengercompose/messengercompose.dtd \
chrome/messenger/content/messenger/messageWindow.xul \
chrome/en-US/locale/en-US/messenger/messenger.dtd \
chrome/messenger/content/messenger/messenger.xul

# uncmment to remove next annoying thunderbird shortcuts - ctrl+enter (send now) and ctrl+shift+enter (send later)
# sed -i -e '/^\s*<!ENTITY [^\.]*Cmd\.keycode "/{  s:^\s*:<!-- :; s:$: -->: ;}' \
#     -i -e '/^\s*<key id="key_send[^"]*" keycode="&[^\.]*Cmd\.keycode;"[^/]*\/[^>]*>$/ { s:^\s*:<!-- :; s:$: -->: ; };' \
# chrome/en-US/locale/en-US/messenger/messengercompose/messengercompose.dtd \
# chrome/messenger/content/messenger/messengercompose/messengercompose.xul

# End of patches
########################################

echo "Repackaging ..."

# repackage omni.ja: - if startup is slow remove the 9 compression and replace it with 0
zip -qr9XD /tmp/newomni.ja *
echo "Backing up original $THUNDERBIRDDIR/omni.ja to $THUNDERBIRDDIR/omni.ja.backup and $HOMEDIR/$BACKUP_OMNI"
cp -v $THUNDERBIRDDIR/omni.ja $HOMEDIR/$BACKUP_OMNI
cp -v $THUNDERBIRDDIR/omni.ja $THUNDERBIRDDIR/$BACKUP_OMNI

echo "Trying to copy /tmp/newomni.ja to $realomnipath"
echo "If this doesn't work, try sudo cp /tmp/newomni.ja $realomnipath"
echo
cp -iv /tmp/newomni.ja $realomnipath

echo 'done!'
